dist: xenial
language: node_js
os: linux
matrix:
  include:
    - node_js: '12'
cache:
  directories: [node_modules]
services:
  - postgresql
install:
  - npm install
before_script:
  - psql -c 'create database movie_test;' -U postgres
  - psql -c 'create database movies;' -U postgres
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage
