environment:
  matrix:
    - nodejs_version: "12"
services:
  - postgresql96
install:
  - psql --version
  - npm install
test_script:
  - psql -c "CREATE DATABASE movie_test;" -U postgres
  - npm test
build: false
