environment:
  matrix:
    - nodejs_version: "12"
  # postgres
  POSTGRES_PORT: tcp://localhost:5432
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!
  POSTGRES_ENV_POSTGRES_DB: movie_test
  POSTGRES_PATH: C:\Program Files\PostgreSQL\9.6
  PGUSER: postgres
  PGPASSWORD: Password12!
init:
  - SET PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
services:
  - postgresql96
install:
  - psql --version
  - echo localhost:*:testdb:postgres:Password12! > C:\Program Files\PostgreSQL\9.6\pgpass.conf
  - echo "localhost:*:testdb:postgres:Password12!" > pgpass.conf
  - echo "localhost:*:testdb:postgres:Password12!" > %userprofile%\pgpass.conf
  - SET PGPASSFILE=C:\Program Files\PostgreSQL\9.6\pgpass.conf
  - set PGPASSWORD=Password12!
  - npm install
test_script:
  - psql -c "CREATE DATABASE movie_test;" -U postgres
  - npm test
build: false
